In [1]:
from pytrends.request import TrendReq
from pytrends import dailydata

In [2]:
df = dailydata.get_daily_data('samoyedcoin', 2020, 11, 2021, 11)
df

dogecoin:2020-11-01 2020-11-30
dogecoin:2020-12-01 2020-12-31
dogecoin:2021-01-01 2021-01-31
dogecoin:2021-02-01 2021-02-28
dogecoin:2021-03-01 2021-03-31
dogecoin:2021-04-01 2021-04-30
dogecoin:2021-05-01 2021-05-31
dogecoin:2021-06-01 2021-06-30
dogecoin:2021-07-01 2021-07-31
dogecoin:2021-08-01 2021-08-31
dogecoin:2021-09-01 2021-09-30
dogecoin:2021-10-01 2021-10-31
dogecoin:2021-11-01 2021-11-30

            dogecoin_unscaled  dogecoin_monthly isPartial  scale  dogecoin
date
2020-11-01                  8               0.0     False   0.00      0.00
2020-11-02                 12               0.0       NaN   0.00      0.00
2020-11-03                  7               0.0       NaN   0.00      0.00
2020-11-04                  8               0.0       NaN   0.00      0.00
2020-11-05                 10               0.0       NaN   0.00      0.00
...                       ...               ...       ...    ...       ...
2021-11-19                 69               4.0       NaN   0.04      2.76
2021-11-20                 65               4.0       NaN   0.04      2.60
2021-11-21                 39               3.0      True   0.03      1.17
2021-11-22                 55               3.0       NaN   0.03      1.65
2021-11-23                 46               3.0       NaN   0.03      1.38

[388 rows x 5 columns]

In [9]:
df.iloc[23:,-1]

date
2020-11-24    1.00
2020-11-25    0.39
2020-11-26    0.23
2020-11-27    0.20
2020-11-28    0.13
              ...
2021-11-19    2.76
2021-11-20    2.60
2021-11-21    1.17
2021-11-22    1.65
2021-11-23    1.38
Name: dogecoin, Length: 365, dtype: float64

In [10]:
df.to_csv('dd_daily_doge_gt.csv')

In [11]:
df2 = dailydata.get_daily_data('samoyedcoin', 2020, 11, 2021, 11)
df2

samoyedcoin:2020-11-01 2020-11-30
samoyedcoin:2020-12-01 2020-12-31
samoyedcoin:2021-01-01 2021-01-31
samoyedcoin:2021-02-01 2021-02-28
samoyedcoin:2021-03-01 2021-03-31
samoyedcoin:2021-04-01 2021-04-30
samoyedcoin:2021-05-01 2021-05-31
samoyedcoin:2021-06-01 2021-06-30
samoyedcoin:2021-07-01 2021-07-31
samoyedcoin:2021-08-01 2021-08-31
samoyedcoin:2021-09-01 2021-09-30
samoyedcoin:2021-10-01 2021-10-31
samoyedcoin:2021-11-01 2021-11-30

,samoyedcoin_unscaled,samoyedcoin_monthly,isPartial,scale,samoyedcoin
date,,,,,
2021-05-01,0,NaN,NaN,NaN,NaN
2021-05-02,0,0.0,False,0.00,0.0
2021-05-03,0,0.0,NaN,0.00,0.0
2021-05-04,0,0.0,NaN,0.00,0.0
2021-05-05,0,0.0,NaN,0.00,0.0
...,...,...,...,...,...
2021-11-19,0,14.0,NaN,0.14,0.0
2021-11-20,0,14.0,NaN,0.14,0.0
2021-11-21,0,0.0,True,0.00,0.0
2021-11-22,0,0.0,NaN,0.00,0.0
2021-11-23,0,0.0,NaN,0.00,0.0

In [12]:
df2 = df2.iloc[23:,-1]

In [13]:
df2.to_csv('dd_daily_samoyed_gt.csv')